Enable setting container to None in winforms
Previous container setter tried to add Controls to the container that is being set, which caused `AttributeError : 'NoneType' object has no attribute 'native'`

Signed-off-by: Olga <obulat@gmail.com>