Enable setting container to None in winforms and gtk
Implementation taken from cocoa backend. Previous container setter tried to add Controls to the container that is being set, which caused `AttributeError : 'NoneType' object has no attribute 'native'` Gtk implementation not tested.

Signed-off-by: Olga <obulat@gmail.com>